# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'green.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_greenUI(object):
    def setupUi(self, greenUI):
        greenUI.setObjectName("greenUI")
        greenUI.resize(800, 450)
        greenUI.setStyleSheet("QMainWindow {\n"
"    border-image: url(:/pic/resource/5.png);\n"
"background-color: rgb(0, 255, 255); \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(greenUI)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(640, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        greenUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(greenUI)
        QtCore.QMetaObject.connectSlotsByName(greenUI)

    def retranslateUi(self, greenUI):
        _translate = QtCore.QCoreApplication.translate
        greenUI.setWindowTitle(_translate("greenUI", "MainWindow"))
        self.buttonBack.setText(_translate("greenUI", "Back"))
import picture_rc
