# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homeUI(object):
    def setupUi(self, homeUI):
        homeUI.setObjectName("homeUI")
        homeUI.resize(800, 450)
        homeUI.setStyleSheet("QMainWindow {\n"
"    border-image: url(:/pic/resource/2.png);    \n"
"    background-color: rgb(0, 255, 255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(homeUI)
        self.centralwidget.setObjectName("centralwidget")
        self.button_red = QtWidgets.QPushButton(self.centralwidget)
        self.button_red.setGeometry(QtCore.QRect(100, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_red.setFont(font)
        self.button_red.setStyleSheet("background:rgb(255, 0, 0)")
        self.button_red.setObjectName("button_red")
        self.button_yellow = QtWidgets.QPushButton(self.centralwidget)
        self.button_yellow.setGeometry(QtCore.QRect(100, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_yellow.setFont(font)
        self.button_yellow.setStyleSheet("background:rgb(255, 255, 0)")
        self.button_yellow.setObjectName("button_yellow")
        self.button_green = QtWidgets.QPushButton(self.centralwidget)
        self.button_green.setGeometry(QtCore.QRect(100, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_green.setFont(font)
        self.button_green.setStyleSheet("background:rgb(0, 255, 0)")
        self.button_green.setObjectName("button_green")
        homeUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(homeUI)
        QtCore.QMetaObject.connectSlotsByName(homeUI)

    def retranslateUi(self, homeUI):
        _translate = QtCore.QCoreApplication.translate
        homeUI.setWindowTitle(_translate("homeUI", "MainWindow"))
        self.button_red.setText(_translate("homeUI", "RED"))
        self.button_yellow.setText(_translate("homeUI", "YELLOW"))
        self.button_green.setText(_translate("homeUI", "GREEN"))
import picture_rc
