# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'red.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_redUI(object):
    def setupUi(self, redUI):
        redUI.setObjectName("redUI")
        redUI.resize(800, 450)
        redUI.setStyleSheet("QMainWindow {\n"
"    border-image: url(:/pic/resource/3.png);\n"
"    background-color: rgb(0, 255, 255); \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(redUI)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(640, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        redUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(redUI)
        QtCore.QMetaObject.connectSlotsByName(redUI)

    def retranslateUi(self, redUI):
        _translate = QtCore.QCoreApplication.translate
        redUI.setWindowTitle(_translate("redUI", "MainWindow"))
        self.buttonBack.setText(_translate("redUI", "Back"))
import picture_rc
