# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yellow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yellowUI(object):
    def setupUi(self, yellowUI):
        yellowUI.setObjectName("yellowUI")
        yellowUI.resize(800, 450)
        yellowUI.setStyleSheet("QMainWindow {\n"
"    border-image: url(:/pic/resource/4.png);\n"
"background-color: rgb(0, 255, 255); \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(yellowUI)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(640, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        yellowUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(yellowUI)
        QtCore.QMetaObject.connectSlotsByName(yellowUI)

    def retranslateUi(self, yellowUI):
        _translate = QtCore.QCoreApplication.translate
        yellowUI.setWindowTitle(_translate("yellowUI", "MainWindow"))
        self.buttonBack.setText(_translate("yellowUI", "Back"))
import picture_rc
